### ISSUE TITLE
Error when clicking on "Update Material List" and "Save Atlas to.." buttons

### ISSUE THREAD

**Issue by Legonzaur** [Grim-es/material-combiner-addon#75]
I get this error when I try to use this plugin : `AttributeError: 'Material' object has no attribute 'texture_slots`

Using Blender 3.5

![image](https://github.com/Grim-es/material-combiner-addon/assets/34353603/89d7c738-9130-4ae2-af35-8ad3657fd1b8)

Screenshot of Blender when I click on "Update material list"
![image](https://github.com/Grim-es/material-combiner-addon/assets/34353603/a178b396-c3cf-4bc0-89a8-b3086556ae90)

Screenshot of Blender when I click on "Save Atlas to.."
![image](https://github.com/Grim-es/material-combiner-addon/assets/34353603/2f0195e5-3c80-43c6-823e-a86168a89348)

**Comment by Grim-es** [comment]
Thanks for the feedback. Looks like on one of materials `Use nodes` is not enabled, so its fallbacked to the method that only works on Blender version 2.79. For now, enable nodes on all materials. The fix i'll push on the next update.

Or until the next update you can manually open [`materials.py`](https://github.com/Grim-es/material-combiner-addon/blob/6572858405720dad0af940df8d59a165e05d1990/utils/materials.py#L83) and on line [83](https://github.com/Grim-es/material-combiner-addon/blob/6572858405720dad0af940df8d59a165e05d1990/utils/materials.py#L83), change:
```
if globs.is_blender_2_80_or_newer and node_tree:
    shader = get_shader_type(mat)
    node_name = shader_image_nodes.get(shader)
    if node_name:
        packed_file = get_packed_file(node_tree.nodes[node_name].image)
```
to:
```
if globs.is_blender_2_80_or_newer:
    if node_tree:
        shader = get_shader_type(mat)
        node_name = shader_image_nodes.get(shader)
        if node_name:
            packed_file = get_packed_file(node_tree.nodes[node_name].image)
```
